name: Verify

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build
        working-directory: packages/cli
        run: yarn build

      - name: Typecheck
        working-directory: packages/cli
        run: yarn typecheck

      - name: Test
        working-directory: packages/cli
        run: yarn test

      - name: Lint
        working-directory: packages/cli
        run: yarn lint
